import { StyleSheet } from "react-native";
import metrics from "../../theme/metrics";
import font from "../../theme/font";
import colors from "../../theme/color";

export const styles = StyleSheet.create({
    mainContainer:{
        flex:1,
        backgroundColor:colors.white,
 
    },
    alignCenter:{
        flex:1,
        alignItems:'center',
        justifyContent:'center'
    },
    appFontStyle:{
        fontSize:font.size.font24,
        fontFamily:font.type.montserratSemiBold,
        color:colors.black,
        includeFontPadding:false,
        top:metrics.changeByMobileDPI(-15)
    },
    appIconStyle:{
        top:metrics.changeByMobileDPI(15)
    },
    subContainer:{

    },
    titleFontStyle:{
        fontSize:font.size.font14,
        fontFamily:font.type.quicksandRegular,
        color:colors.black,
        marginLeft:metrics.changeByMobileDPI(10),
        top:metrics.changeByMobileDPI(-2)
    },
    subTitleFontStyle:{
        fontSize:font.size.font14,
        fontFamily:font.type.quicksandMedium,
        color:colors.graySolid,
        textAlign:'center',
        marginBottom:metrics.changeByMobileDPI(20),
        marginHorizontal:metrics.changeByMobileDPI(20)
    },
    infoFontStyle:{
        fontSize:font.size.font14,
        fontFamily:font.type.quicksandRegular,
        color:colors.black,
        marginBottom:metrics.changeByMobileDPI(40),
        marginHorizontal:metrics.changeByMobileDPI(20)
    },
    guidenceFontStyleButLinkcolor:{
        fontSize:font.size.font12,
        fontFamily:font.type.quicksandMedium,
        color:colors.linkBlue ,
    },
    guidenceFontStyle:{
        fontSize:font.size.font12,
        fontFamily:font.type.quicksandMedium,
        color:colors.graySolid,
        textAlign:'center'
    },
    extrenalStyle:{
        marginVertical:metrics.changeByMobileDPI(20),
        marginHorizontal:metrics.changeByMobileDPI(35)
    },
    svgContainer:{
        alignItems:'center'
      },
      contentContainerStyle:{
        marginLeft:metrics.changeByMobileDPI(17)
      },
      flexDirectionContainer:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        marginHorizontal:metrics.changeByMobileDPI(20),
        marginTop:metrics.changeByMobileDPI(20)
      },
      verificationContainer:{
        backgroundColor:colors.white,
        flex:1,
        borderRadius:metrics.changeByMobileDPI(20)
      },
      gridentConatiner: {
        height: metrics.changeByMobileDPI(39),
        flex:1,
        overflow: 'hidden',
        marginHorizontal:metrics.changeByMobileDPI(20),
        borderRadius:metrics.changeByMobileDPI(20)
    },
    gridentConatiner2:{
        flex:1,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center',
    },
    alignmentContainer:{
        alignItems:'center',
        justifyContent:'center', 
        flexDirection:'row',
        flex:1
    },
    externalStyle:{
        height:metrics.changeByMobileDPI(398),
        marginTop:metrics.changeByMobileDPI(20),
        width:metrics.screenWidth / 1.3
    },
    alignSelfContainer:{
        alignItems:'center'
    },
    eventFontStyle:{
        fontSize:font.size.font12,
        fontFamily:font.type.montserratRegular,
        color:colors.black,
    },
    rowContainer:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        marginHorizontal:metrics.changeByMobileDPI(20),
        marginVertical:metrics.changeByMobileDPI(10)
    },
    imageSytle:{
        height:metrics.changeByMobileDPI(24),
        width:metrics.changeByMobileDPI(24),
        borderRadius:metrics.changeByMobileDPI(100),
        marginRight:metrics.changeByMobileDPI(10)
    },
    nameFontStyle:{
        fontSize:font.size.font20,
        fontFamily:font.type.quicksandBold,
        color:colors.black,
    },
    ageFontStyle:{
        fontSize:font.size.font13,
        fontFamily:font.type.quicksandRegular,
        color:colors.black,
        alignSelf:'center'
    },
    nationailtyFontStyle:{
        fontSize:font.size.font10,
        fontFamily:font.type.quicksandRegular,
        color:colors.black,
        marginRight:metrics.changeByMobileDPI(10)
    },
    descriptionFontStyle:{
        fontSize:font.size.font13,
        fontFamily:font.type.quicksandRegular,
        color:colors.graySolid,   
    },
    flexRowContainer:{
        flexDirection:'row',
        alignItems:'center'
    },
    centerProfileContainer:{
      flex:1,
    //   backgroundColor:'red',
      alignItems:'center'
    },
    profileContainer:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center'
    },
    nationailtyContainier:{
        height:metrics.changeByMobileDPI(23.5),
        backgroundColor:colors.gray,
        borderRadius:metrics.changeByMobileDPI(100),
        flexDirection:'row',
        alignItems:'center',
        paddingHorizontal:metrics.changeByMobileDPI(10),
        marginRight:metrics.changeByMobileDPI(10)
    },
    descriptionContainer:{
        flex:1,
        marginHorizontal:metrics.changeByMobileDPI(20)
    },
    postionContainer:{
      position:'absolute',
      right:metrics.changeByMobileDPI(20)
    },
    flexContainer:{
        flex:1,
    },
    profileTitleFontStyle:{
        fontSize:font.size.font14,
        fontFamily:font.type.montserratRegular,
        color:colors.black, 
    },
    profileDescriptionFontStyle:{
        fontSize:font.size.font12,
        fontFamily:font.type.montserratRegular,
        color:colors.graySolid, 
    },
    profileSvgContainer:{
        marginRight:metrics.changeByMobileDPI(10)
    },
    usreInforamtionContainer:{
        marginHorizontal:metrics.changeByMobileDPI(20),
    },
    proileFlexRowContainer:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        marginTop:metrics.changeByMobileDPI(20)
    },
    userInFoTitleFontStyle:{
        fontSize:font.size.font14,
        fontFamily:font.type.quicksandRegular,
        color:colors.black,  
        marginTop:metrics.changeByMobileDPI(20)

    },
    globalTitleFontStyle:{
        fontSize:font.size.font14,
        fontFamily:font.type.quicksandRegular,
        color:colors.black,  
        marginTop:metrics.changeByMobileDPI(20)  ,
        marginHorizontal:metrics.changeByMobileDPI(20),
        marginBottom:metrics.changeByMobileDPI(20)
    },
    likeRowContainer:{
        marginHorizontal:metrics.changeByMobileDPI(20),
        flexDirection:'row',
    },
    dotContainer:{
        height:metrics.changeByMobileDPI(3.5),
        width:metrics.changeByMobileDPI(3.5),
        borderRadius:metrics.changeByMobileDPI(100),
        backgroundColor:colors.graySolid,
        marginTop:metrics.changeByMobileDPI(8),
        marginRight:metrics.changeByMobileDPI(5)
    },
    likeFontStyle:{
        fontSize:font.size.font13,
        fontFamily:font.type.quicksandRegular,
        color:colors.graySolid, 
         includeFontPadding:false
    },
    exterContainerStyle:{
        marginBottom:0
    },
    marginTopContainer:{
        marginTop:metrics.changeByMobileDPI(20)
    },
    flagStyle:{
        height:metrics.changeByMobileDPI(13.5),
        width:metrics.changeByMobileDPI(18)
    },
    buttonStyle:{
        height:30,
        width:metrics.screenWidth,
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:colors.secondary
    }
})
