import { StyleSheet } from "react-native";
import metrics from "../../theme/metrics";
import font from "../../theme/font";
import colors from "../../theme/color";

export const styles = StyleSheet.create({
    mainContainer:{
        flex:1,
        backgroundColor:colors.white
    },
    alignCenter:{
        flex:1,
        alignItems:'center',
        justifyContent:'center'
    },
    appFontStyle:{
        fontSize:font.size.font24,
        fontFamily:font.type.montserratSemiBold,
        color:colors.black,
        includeFontPadding:false,
        top:metrics.changeByMobileDPI(-15)
    },
    appIconStyle:{
        top:metrics.changeByMobileDPI(15)
    },
    subContainer:{
    },
    titleFontStyle:{
        fontSize:font.size.font16,
        fontFamily:font.type.quicksandRegular,
        color:colors.black,
        textAlign:'center',
        marginTop:metrics.changeByMobileDPI(15),
        marginBottom:metrics.changeByMobileDPI(20),
    },
    subTitleFontStyle:{
        fontSize:font.size.font14,
        fontFamily:font.type.quicksandMedium,
        color:colors.graySolid,
        textAlign:'center',
        marginBottom:metrics.changeByMobileDPI(20),
        marginHorizontal:metrics.changeByMobileDPI(20)
    },
    infoFontStyle:{
        fontSize:font.size.font14,
        fontFamily:font.type.quicksandRegular,
        color:colors.black,
        marginBottom:metrics.changeByMobileDPI(20),
        marginHorizontal:metrics.changeByMobileDPI(20)
    },
    guidenceFontStyleButLinkcolor:{
        fontSize:font.size.font12,
        fontFamily:font.type.quicksandMedium,
        color:colors.linkBlue ,
    },
    guidenceFontStyle:{
        fontSize:font.size.font12,
        fontFamily:font.type.quicksandMedium,
        color:colors.graySolid,
        textAlign:'center'
    },
    extrenalStyle:{
        marginVertical:metrics.changeByMobileDPI(20),
        marginHorizontal:metrics.changeByMobileDPI(35)
    },
    termAndConditionContianer:{
        marginHorizontal:metrics.changeByMobileDPI(20)
    },
    textFontsStyle:{
        fontSize:font.size.font25,
        fontFamily:font.type.latoBold
    },
    positionContainer:{
        position:'absolute',
        top:0,
        left:0,
        right:0,
        bottom:0,
        zIndex:100,
        backgroundColor:'red'
    },
    webview:{
        flex:1
    },
    flexDirectionContainer:{
        flexDirection:'row',
        alignItems:'center',
        borderTopWidth:1,
        borderBottomWidth:1,
        borderColor:colors.grayMedium,
        height:metrics.changeByMobileDPI(168),
        marginBottom:metrics.changeByMobileDPI(30),
        marginTop:metrics.changeByMobileDPI(20)
    },
    flexContainer:{
        flex:1,
        alignItems:'center'
    },
    verticaleLine:{
        width:0.9,
        backgroundColor:colors.graySolid,
        height:'97%',
        alignSelf:'center',
        marginVertical:metrics.changeByMobileDPI(1)
    },
    itemFontStyle:{
        fontSize:font.size.font14,
        fontFamily:font.type.quicksandRegular,
        color:colors.black,
        marginBottom:metrics.changeByMobileDPI(9)
    },
    bronzeFontStyle:{
        fontSize:font.size.font12,
        fontFamily:font.type.quicksandMedium,
        color:colors.graySolid,
        marginBottom:metrics.changeByMobileDPI(9)

    },
    taxFontStyle:{
        fontSize:font.size.font12,
        fontFamily:font.type.quicksandMedium,
        color:colors.graySolid,
        marginBottom:metrics.changeByMobileDPI(9)

    },
    totalFontStyle:{
        fontSize:font.size.font14,
        fontFamily:font.type.quicksandRegular,
        color:colors.black,

    },
    justifyCenterContainer:{
        flex:1,
        justifyContent:'center',
        alignItems:'center'
    }
})
