import { Platform, StyleSheet } from "react-native";
import metrics from "../../theme/metrics";
import font from "../../theme/font";
import colors from "../../theme/color";

export const styles = StyleSheet.create({
    mainContainer:{
        flex:1,
        backgroundColor:colors.white,
 
    },
    alignCenter:{
        flex:1,
        alignItems:'center',
        justifyContent:'center'
    },
    appFontStyle:{
        fontSize:font.size.font24,
        fontFamily:font.type.montserratSemiBold,
        color:colors.black,
        includeFontPadding:false,
        top:metrics.changeByMobileDPI(-15)
    },
    appIconStyle:{
        top:metrics.changeByMobileDPI(15)
    },
    subContainer:{
      height:metrics.screenHeight/ 1.2,
      // paddingBottom:metrics.changeByMobileDPI(20)
    },
    titleFontStyle:{
        fontSize:font.size.font16,
        fontFamily:font.type.montserratBold,
        color:colors.boy_gray,
        marginHorizontal:metrics.changeByMobileDPI(20),
        marginBottom:metrics.changeByMobileDPI(20)
    },
  
 
      contentContainerStyle:{
        paddingLeft:metrics.changeByMobileDPI(20),
        paddingRight:metrics.changeByMobileDPI(10)
      },

      quickLinFontStyle:{
        fontSize:font.size.font12,
        fontFamily:font.type.montserratRegular,
        color:colors.black,
        marginTop:metrics.changeByMobileDPI(10)
      },

      imageStyle:{
        height:'100%',
     width:'100%',
    },
    quickLinkMainContainer:{
        alignItems:'center',
        marginRight:metrics.changeByMobileDPI(10)
    },
    margnBottomContainer:{
      marginBottom:metrics.changeByMobileDPI(20)
    },
    
    chatListingTitleFontStyle:{
      fontSize:font.size.font16,
      fontFamily:font.type.montserratMedium,
      color:colors.black,
    },
    chatLisitingMessageFontStyle:{
      fontSize:font.size.font12,
      fontFamily:font.type.montserratRegular,
      color:colors.graySolid,
    },
    seenFontStyle:{
      fontSize:font.size.font12,
      fontFamily:font.type.montserratRegular,
      color:'#3C3C4360',
      marginLeft:metrics.changeByMobileDPI(10),
    },
    timeFontStyle:{
      fontSize:font.size.font12,
      fontFamily:font.type.montserratRegular,
      color:'#3C3C4360',
    },
    flexContainerSubContainer:{
      flexDirection:'row',
      alignItems:'center',
    },
    flexContainer:{
      borderBottomWidth:0.5,
      borderBottomColor:colors.gray_75,
      marginBottom:metrics.changeByMobileDPI(20),
      paddingHorizontal:metrics.changeByMobileDPI(20),
      paddingBottom:metrics.changeByMobileDPI(15),
      
    },
    marginLeftContainer:{
      marginLeft:metrics.changeByMobileDPI(10),
      flex:1
    },
    messageContainer:{
      marginBottom:metrics.changeByMobileDPI(7)
    },
    searchContainer:{
      flexDirection:'row',
      alignItems:'center',
      marginHorizontal:metrics.changeByMobileDPI(20),
      marginVertical:metrics.changeByMobileDPI(30)
    },
    searchSubContianer:{
      height:metrics.changeByMobileDPI(48.94),
      borderRadius:metrics.changeByMobileDPI(8),
      backgroundColor:colors.lightGrayBgColor,
      flexDirection:'row',
      alignItems:'center',
      flex:1,
      marginHorizontal:metrics.changeByMobileDPI(10)
    },
    inputStyle:{
      height:metrics.changeByMobileDPI(48.94),
      fontSize:font.size.font14,
      fontFamily:font.type.montserratRegular,
      color:colors.black,
    },
    inputContainer:{
      flex:1
    },
    marginContainer:{
      marginHorizontal:metrics.changeByMobileDPI(10)
    },
    doubleTickcontainer:{
      flexDirection:'row',
      alignItems:'center'
    },
    gridentButtonStyle:{
      height:metrics.changeByMobileDPI(24),
   width:metrics.changeByMobileDPI(24),
   borderRadius:metrics.changeByMobileDPI(100),
   alignItems:'center',
   justifyContent:'center',
   overflow:'hidden'
    },
    countFontStyle:{
      fontSize:font.size.font12,
      fontFamily:font.type.montserratRegular,
      color:colors.white,
      paddingHorizontal:metrics.changeByMobileDPI(5)
    },
    countSubContainer:{
      flex:1,
      borderRadius:metrics.changeByMobileDPI(100),
    },


    ///
    flexDirectionHeaderContainer:{
      flexDirection:'row',
      alignItems:'center',
      justifyContent:'space-between',
      marginHorizontal:metrics.changeByMobileDPI(20),
      marginTop:metrics.changeByMobileDPI(20),
      marginBottom:metrics.changeByMobileDPI(10)
    },
    headerFontStyle:{
      fontSize:font.size.font14,
      fontFamily:font.type.montserratMedium,
      color:colors.black,
    },
    imageMainContainer:{
      flexDirection:'row',
      alignItems:'center'
    },
    profileImageContainer:{
      height:metrics.changeByMobileDPI(43),
      width:metrics.changeByMobileDPI(43),
      borderRadius:metrics.changeByMobileDPI(100),
      overflow:'hidden',
      marginRight:metrics.changeByMobileDPI(10)
    },
    flexDirectionContainer:{
      flexDirection:'row',
      alignItems:'center'
    },
    marginRightContainer:{
      marginRight:metrics.changeByMobileDPI(10)
    },
    positionContainer:{
      position:'absolute',
      left:0,
      right:0,
       top:0,
       bottom:0,
       backgroundColor:'#00000070',
       zIndex:100
    },
    selectFontStyle:{
      fontSize:font.size.font16,
      fontFamily:font.type.montserratRegular,
      color:colors.black,
      marginLeft:metrics.changeByMobileDPI(10)
    },
    flexDirection:{
      flexDirection:'row',
      alignItems:'center',
      marginBottom:metrics.changeByMobileDPI(20)
    },
    selectContainer:{
      flex:1,
    },
    selectSubContainer:{
      marginHorizontal:metrics.changeByMobileDPI(20),
      marginTop:metrics.changeByMobileDPI(0)
    },
    inputMainContainer:{
      flexDirection:'row',
      alignItems:'center',
      // borderTopWidth:1,
      // borderColor:colors.graySolid,
      height:metrics.changeByMobileDPI(48),
      width:metrics.screenWidth,
      paddingHorizontal:metrics.changeByMobileDPI(20),
      backgroundColor:colors.white,
      marginBottom:10
    },
    inputPosiiton:{
      position:'absolute',
      bottom:Platform.OS == 'android' ? 0 : metrics.changeByMobileDPI(20),
    },
    sendFontStyle:{
      fontSize:font.size.font16,
      fontFamily:font.type.montserratRegular,
      color:colors.graySolid,
    },
    flexStyle:{
      flex:1,
      borderWidth:1,
      borderColor:colors.graySolid,
      borderRadius:metrics.changeByMobileDPI(100),
      paddingHorizontal:metrics.changeByMobileDPI(10),
      marginRight:metrics.changeByMobileDPI(10)
    },
    messageFontStyle:{
      fontSize:font.size.font16,
      fontFamily:font.type.montserratRegular,
      color:colors.black,
      includeFontPadding:false
    },
    messageWhiteFontStyle:{
      fontSize:font.size.font16,
      fontFamily:font.type.montserratRegular,
      color:colors.white,
      includeFontPadding:false
    },
    chatContainer:{
    },
    leftMessageContainer:{
      maxWidth:metrics.screenWidth / 2,
       paddingVertical:metrics.changeByMobileDPI(10),
       borderTopLeftRadius:metrics.changeByMobileDPI(15),
       borderTopRightRadius:metrics.changeByMobileDPI(15),
       borderBottomLeftRadius:0,
       borderBottomRightRadius:metrics.changeByMobileDPI(15),
       backgroundColor:colors.lightGray,
       paddingHorizontal:metrics.changeByMobileDPI(15),

    },
    leftContainer:{
      flexDirection:'row',
      alignItems:'center',
      justifyContent:'space-between',
      marginBottom:metrics.changeByMobileDPI(15),
      marginHorizontal:metrics.changeByMobileDPI(20),
      alignSelf:'flex-start'
    },
    rightContainer:{
      marginBottom:metrics.changeByMobileDPI(15),
      marginHorizontal:metrics.changeByMobileDPI(20),
      alignSelf:'flex-end'
    },
    rightMessageContainer:{
      maxWidth:metrics.screenWidth / 2,
      paddingVertical:metrics.changeByMobileDPI(10),
      borderTopLeftRadius:metrics.changeByMobileDPI(15),
      borderTopRightRadius:metrics.changeByMobileDPI(15),
      borderBottomLeftRadius:metrics.changeByMobileDPI(15),
      borderBottomRightRadius:metrics.changeByMobileDPI(0),
      backgroundColor:colors.pink,
      paddingHorizontal:metrics.changeByMobileDPI(15),


   },
   flexLeftContainer:{
    flex:1,
    alignItems:'flex-end'
   },
   flexSeenContainer:{
    flexDirection:'row',
    alignItems:'center',
    marginTop:metrics.changeByMobileDPI(5),
    justifyContent:'flex-end'
   },
   circleContainer:{
    height:metrics.changeByMobileDPI(40),
    width:metrics.changeByMobileDPI(40),
    borderRadius:metrics.changeByMobileDPI(100),
    backgroundColor:colors.primary,
    alignItems:'center',
    justifyContent:'center'
   },
   imageBackgroundMainContianer:{
    height:'100%',
    width:'100%',
 
   }
})
