export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
////////
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SGNUP_FAILURE = 'SIGNUP_FAILURE';
////////
export const ONBORDING_REQUEST = 'ONBORDING_REQUEST';
export const ONBORDING_SUCCESS = 'ONBORDING_SUCCESS';
export const ONBORDING_FAILURE = 'ONBORDING_FAILURE';
////////
export const DEVICEANDLOCATION_REQUEST = 'DEVICEANDLOCATION_REQUEST';
export const LOADER = 'LOADER';
//
export const UPCOMINGEVENT_REQUEST = 'UPCOMINGEVENT_REQUEST';
export const UPCOMINGEVENT_SUCCESS = 'UPCOMINGEVENT_SUCCESS';
export const UPCOMINGEVENT_FAILURE = 'UPCOMINGEVENT_FAILURE';
//
export const OURSERVICE_REQUEST = 'OURSERVICE_REQUEST';
export const OURSERVICE_SUCCESS = 'OURSERVICE_SUCCESS';
export const OURSERVICE_FAILURE = 'OURSERVICE_FAILURE';
// 
export const ALLEVENT_REQUEST = 'ALLEVENT_REQUEST';
export const ALLEVENT_SUCCESS = 'ALLEVENT_SUCCESS';
export const ALLEVENT_FAILURE = 'ALLEVENT_FAILURE';
///
export const WISHLIST_REQUEST = 'WISHLIST_REQUEST';
export const WISHLIST_SUCCESS = 'WISHLIST_SUCCESS';
export const WISHLIST_FAILURE = 'WISHLIST_FAILURE';
///
export const EVENTDETAIL_REQUEST = 'EVENTDETAIL_REQUEST';
export const EVENTDETAIL_SUCCESS = 'EVENTDETAIL_SUCCESS';
export const EVENTDETAIL_FAILURE = 'EVENTDETAIL_FAILURE';
///
export const SERVICES_REQUEST = 'SERVICES_REQUEST';
export const SERVICES_SUCCESS = 'SERVICES_SUCCESS';
export const SERVICES_FAILURE = 'SERVICES_FAILURE';
///
export const SERVICES_DETAIL_REQUEST = 'SERVICES_DETAIL_REQUEST';
export const SERVICES_DETAIL_SUCCESS = 'SERVICES_DETAIL_SUCCESS';
export const SERVICES_DETAIL_FAILURE = 'SERVICES_DETAIL_FAILURE';
///
export const PAYMENT_REQUEST = 'PAYMENT_REQUEST';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const PAYMENT_FAILURE = 'PAYMENT_FAILURE';
///
export const PAYMENT_STATUS_REQUEST = 'PAYMENT_STATUS_REQUEST';
export const PAYMENT_STATUS_SUCCESS = 'PAYMENT_STATUS_SUCCESS';
export const PAYMENT_STATUS_FAILURE = 'PAYMENT_STATUS_FAILURE';

///
export const PAYMENT_ORDER_DETAIL_REQUEST = 'PAYMENT_ORDER_DETAIL_REQUEST';
export const PAYMENT_ORDER_DETAIL_SUCCESS = 'PAYMENT_ORDER_DETAIL_SUCCESS';
export const PAYMENT_ORDER_DETAIL_FAILURE = 'PAYMENT_ORDER_DETAIL_FAILURE';
////
export const SIGNOUT_REQUEST = 'SIGNOUT_REQUEST';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNOUT_FAILURE = 'SIGNOUT_SUCCESS';
///
export const ACCOUNTDELETE_REQUEST = 'ACCOUNTDELETE_REQUEST';
export const ACCOUNTDELETE_SUCCESS = 'ACCOUNTDELETE_SUCCESS';
export const ACCOUNTDELETE_FAILURE = 'ACCOUNTDELETE_FAILURE';

///
export const USEREXIST_REQUEST = 'USEREXIST_REQUEST';
export const USEREXIST_SUCCESS = 'USEREXIST_SUCCESS';
export const USEREXIST_FAILURE = 'USEREXIST_FAILURE';

export const ATTANDEES_REQUEST = 'ATTANDEES_REQUEST';
export const ATTANDEES_SUCCESS = 'ATTANDEES_SUCCESS';
export const ATTANDEES_FAILURE = 'ATTANDEES_FAILURE';


export const GET_PLAN_REQUEST = 'GET_PLAN_REQUEST';
export const GET_PLAN_SUCCESS = 'GET_PLAN_SUCCESS';
export const GET_PLAN_FAILURE = 'GET_PLAN_FAILURE';

export const GET_COUNTRY_REQUEST = 'GET_COUNTRY_REQUEST';
export const GET_COUNTRY_SUCCESS = 'GET_COUNTRY_SUCCESS';
export const GET_COUNTRY_FAILURE = 'GET_COUNTRY_FAILURE';

export const SUBSCRIPITON_DETAIL_REQUEST = 'SUBSCRIPITON_DETAIL_REQUEST';
export const SUBSCRIPITON_DETAIL_SUCCESS = 'SUBSCRIPITON_DETAIL_SUCCESS';
export const SUBSCRIPITON_DETAIL_FAILURE = 'SUBSCRIPITON_DETAIL_FAILURE';

export const MY_FAN_REQUEST = 'MY_FAN_REQUEST';
export const MY_FAN_SUCCESS = 'MY_FAN_SUCCESS';
export const MY_FAN_FAILURE = 'MY_FAN_FAILURE';

export const GET_USER_REPORT_REQUEST = 'GET_USER_REPORT_REQUEST';
export const GET_USER_REPORT_SUCCESS = 'GET_USER_REPORT_SUCCESS';
export const GET_USER_REPORT_FAILURE = 'GET_USER_REPORT_FAILURE';

export const ADD_REPORT_REQUEST = 'ADD_REPORT_REQUEST';
export const ADD_REPORT_SUCCESS = 'ADD_REPORT_SUCCESS';
export const ADD_REPORT_FAILURE = 'ADD_REPORT_FAILURE';


export const FETCH_STATIC_REQUEST = 'FETCH_STATIC_REQUEST';
export const FETCH_STATIC_SUCCESS = 'FETCH_STATIC_SUCCESS';
export const FETCH_STATIC_FAILURE = 'FETCH_STATIC_FAILURE';

export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';


export const GET_FRIEND_REQUEST = 'GET_FRIEND_REQUEST';
export const GET_FRIEND_SUCCESS = 'GET_FRIEND_SUCCESS';
export const GET_FRIEND_FAILURE = 'GET_FRIEND_FAILURE';

export const GET_USERDETAIL_REQUEST = 'GET_USERDETAIL_REQUEST';
export const GET_USERDETAIL_SUCCESS = 'GET_USERDETAIL_SUCCESS';
export const GET_USERDETAIL_FAILURE = 'GET_USERDETAIL_FAILURE';


export const MATCH_OPERATION_REQUEST = 'MATCH_OPERATION_REQUEST';
export const MATCH_OPERATION_SUCCESS = 'MATCH_OPERATION_SUCCESS';
export const MATCH_OPERATION_FAILURE = 'MATCH_OPERATION_FAILURE';

export const MATCH_PROFILE_REQUEST = 'MATCH_PROFILE_REQUEST';
export const MATCH_PROFILE_SUCCESS = 'MATCH_PROFILE_SUCCESS';
export const MATCH_PROFILE_FAILURE = 'MATCH_PROFILE_FAILURE';

export const WEB_INDEX_REQUEST = 'WEB_INDEX_REQUEST';
export const WEB_INDEX_SUCCESS = 'WEB_INDEX_SUCCESS';
export const WEB_INDEX_FAILURE = 'WEB_INDEX_FAILURE';

export const GLOBAL_DRAWER = 'GLOBAL_DRAWER';
// 

export const NOTIIFICATION_LIST_REQUEST = 'NOTIIFICATION_LIST_REQUEST';
export const NOTIIFICATION_LIST_SUCCESS = 'NOTIIFICATION_LIST_SUCCESS';
export const NOTIIFICATION_LIST_FAILURE = 'NOTIIFICATION_LIST_FAILURE';

export const GET_COMPANY_REQUEST = 'GET_COMPANY_REQUEST';
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS';
export const GET_COMPANY_FAILURE = 'GET_COMPANY_FAILURE';

export const SHARE_DATA_COMPANY_REQUEST = 'SHARE_DATA_COMPANY_REQUEST';
export const SHARE_DATA_COMPANY_SUCCESS = 'SHARE_DATA_COMPANY_SUCCESS';
export const SHARE_DATA_COMPANY_FAILURE = 'SHARE_DATA_COMPANY_FAILURE';

export const GET_ORDERDETAIL_REQUEST = 'GET_ORDERDETAIL_REQUEST';
export const GET_ORDERDETAIL_SUCCESS = 'GET_ORDERDETAIL_SUCCESS';
export const GET_ORDERDETAIL_FAILURE = 'GET_ORDERDETAIL_FAILURE';

export const GET_PLANDETAIL_REQUEST = 'GET_PLANDETAIL_REQUEST';
export const GET_PLANDETAIL_SUCCESS = 'GET_PLANDETAIL_SUCCESS';
export const GET_PLANDETAIL_FAILURE = 'GET_PLANDETAIL_FAILURE';

export const INITIATE_REFUND_REQUEST = 'INITIATE_REFUND_REQUEST';
export const INITIATE_REFUND_SUCCESS = 'INITIATE_REFUND_SUCCESS';
export const INITIATE_REFUND_FAILURE = 'INITIATE_REFUND_FAILURE';

export const  THUMBNAIL = 'THUMBNAIL';


// ID VERIFICATION

export const UPLOAD_IDVERIFICATION_IMAGE_REQUEST = 'UPLOAD_IDVERIFICATION_IMAGE_REQUEST';
export const UPLOAD_IDVERIFICATION_IMAGE_SUCCESS = 'UPLOAD_IDVERIFICATION_IMAGE_SUCCESS';
export const UPLOAD_IDVERIFICATION_IMAGE_FAILURE = 'UPLOAD_IDVERIFICATION_IMAGE_FAILURE';

export const UPLOAD_IDVERIFICATION_VIDEO_REQUEST = 'UPLOAD_IDVERIFICATION_VIDEO_REQUEST';
export const UPLOAD_IDVERIFICATION_VIDEO_SUCCESS = 'UPLOAD_IDVERIFICATION_VIDEO_SUCCESS';
export const UPLOAD_IDVERIFICATION_VIDEO_FAILURE = 'UPLOAD_IDVERIFICATION_VIDEO_FAILURE';