import { StyleSheet } from "react-native";
import metrics from "../../theme/metrics";
import font from "../../theme/font";
import colors from "../../theme/color";

export const styles = StyleSheet.create({
    mainContainer:{
        flex:1,
        backgroundColor:colors.white,
        justifyContent:'center',
        alignItems:'center'
    },
    alignCenter:{
        flex:1,
        alignItems:'center',
        justifyContent:'center'
    },
    appFontStyle:{
        fontSize:font.size.font24,
        fontFamily:font.type.montserratSemiBold,
        color:colors.black,
        includeFontPadding:false,
        top:metrics.changeByMobileDPI(-15)
    },
    appIconStyle:{
        top:metrics.changeByMobileDPI(15)
    },
    subContainer:{
        flex:1
    },
    titleFontStyle:{
        fontSize:font.size.font47,
        fontFamily:font.type.latoSemiBold,
        color:colors.white,
        textAlign:'center',
        marginTop:metrics.changeByMobileDPI(15),
        marginBottom:metrics.changeByMobileDPI(20),
    },
    subTitleFontStyle:{
        fontSize:font.size.font14,
        fontFamily:font.type.quicksandMedium,
        color:colors.white,
        textAlign:'center',
        marginBottom:metrics.changeByMobileDPI(20),
        marginHorizontal:metrics.changeByMobileDPI(20),
        marginTop:metrics.changeByMobileDPI(20)
    },
    infoFontStyle:{
        fontSize:font.size.font14,
        fontFamily:font.type.quicksandRegular,
        color:colors.black,
        marginBottom:metrics.changeByMobileDPI(40),
        marginHorizontal:metrics.changeByMobileDPI(20)
    },
    guidenceFontStyleButLinkcolor:{
        fontSize:font.size.font12,
        fontFamily:font.type.quicksandMedium,
        color:colors.linkBlue ,
    },
    guidenceFontStyle:{
        fontSize:font.size.font12,
        fontFamily:font.type.quicksandMedium,
        color:colors.graySolid,
        textAlign:'center'
    },
    extrenalStyle:{
        marginVertical:metrics.changeByMobileDPI(20),
        marginHorizontal:metrics.changeByMobileDPI(35)
    },
 
    imageStyle:{
        height:'100%',
        width:'100%'
      },
      positionContainer:{
        position:'absolute',
        top:0,
        bottom:0,
        left:0,
        right:0,
        zIndex:0
      },
      gridentButtonStyle:{
        position:'absolute',
        top:0,
        bottom:0,
        left:0,
        right:0, 
        zIndex:100,
      },
      imageMatchMakingCircleStyle:{
   height:metrics.changeByMobileDPI(131),
   width:metrics.changeByMobileDPI(131),
   borderRadius:metrics.changeByMobileDPI(100),
   borderWidth:4,
   borderColor:colors.white,
   overflow:'hidden'
      },
      imageMatchMakingCircleStyle2:{
        height:metrics.changeByMobileDPI(131),
        width:metrics.changeByMobileDPI(131),
        borderRadius:metrics.changeByMobileDPI(100),
        borderWidth:4,
        borderColor:colors.white,
        overflow:'hidden',
        left:metrics.changeByMobileDPI(-20)
      },
      imageMainContainer:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center',
        marginLeft:metrics.changeByMobileDPI(20)
      }
})
