import { StyleSheet } from "react-native";
import metrics from "../../theme/metrics";
import font from "../../theme/font";
import colors from "../../theme/color";

export const styles = StyleSheet.create({
    mainContainer:{
        flex:1,
        backgroundColor:colors.white,
        justifyContent:'center',
    },
    alignCenter:{
        flex:1,
        alignItems:'center',
        justifyContent:'center'
    },
    appFontStyle:{
        fontSize:font.size.font24,
        fontFamily:font.type.montserratSemiBold,
        color:colors.black,
        includeFontPadding:false,
        top:metrics.changeByMobileDPI(-15)
    },
    appIconStyle:{
        top:metrics.changeByMobileDPI(15)
    },
    subContainer:{
    },
    titleFontStyle:{
        fontSize:font.size.font24,
        fontFamily:font.type.latoSemiBold,
        color:colors.black,
        textAlign:'center',
        marginTop:metrics.changeByMobileDPI(15),
        marginBottom:metrics.changeByMobileDPI(20),
    },
    purchaseFontStyle:{
        fontSize:font.size.font14,
        fontFamily:font.type.latoSemiBold,
        color:colors.black,
        textAlign:'center',
        marginBottom:metrics.changeByMobileDPI(20)
    },
    subTitleFontStyle:{
        fontSize:font.size.font14,
        fontFamily:font.type.quicksandMedium,
        color:colors.graySolid,
        textAlign:'center',
        marginBottom:metrics.changeByMobileDPI(20),
        marginHorizontal:metrics.changeByMobileDPI(40)
    },
    infoFontStyle:{
        fontSize:font.size.font14,
        fontFamily:font.type.quicksandRegular,
        color:colors.black,
        marginBottom:metrics.changeByMobileDPI(20),
        marginHorizontal:metrics.changeByMobileDPI(20)
    },
    guidenceFontStyleButLinkcolor:{
        fontSize:font.size.font12,
        fontFamily:font.type.quicksandMedium,
        color:colors.linkBlue ,
    },
    guidenceFontStyle:{
        fontSize:font.size.font12,
        fontFamily:font.type.quicksandMedium,
        color:colors.graySolid,
        textAlign:'center'
    },
    extrenalStyle:{
        marginVertical:metrics.changeByMobileDPI(20),
        marginHorizontal:metrics.changeByMobileDPI(35)
    },
    termAndConditionContianer:{
        marginHorizontal:metrics.changeByMobileDPI(20)
    },
    textFontsStyle:{
        fontSize:font.size.font25,
        fontFamily:font.type.latoBold
    },
    maleContainer:{
        
    },
    contentContainerStyle:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center',
        marginVertical:metrics.changeByMobileDPI(20)
    },
    maleFontStyle:{
        fontSize:font.size.font12,
        fontFamily:font.type.quicksandRegular,
        color:colors.black,
    },
    marginRightContiner:{
        marginRight:metrics.changeByMobileDPI(15)
    },
    flexDirectionContainer:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        marginVertical:metrics.changeByMobileDPI(30),
        marginRight:metrics.changeByMobileDPI(10)
    },
    marginBottomContainer:{
        marginBottom:metrics.changeByMobileDPI(10)
    },
    slotsContainer:{
        height:metrics.changeByMobileDPI(75),
        width:metrics.changeByMobileDPI(75),
        borderRadius:metrics.changeByMobileDPI(5),
        borderWidth:1,
        borderColor:colors.tomatoRed,
        alignItems:'center',
        justifyContent:'center',
    
    },
    warningFontStyle:{
        fontSize:font.size.font14,
        fontFamily:font.type.quicksandRegular,
        color:colors.black,
    },
    descriptionFontStyle:{
        fontSize:font.size.font12,
        fontFamily:font.type.quicksandMedium,
        color:colors.graySolid,
        marginTop:metrics.changeByMobileDPI(20),
        marginHorizontal:metrics.changeByMobileDPI(5)
    },
    warningContainer:{
        marginBottom:metrics.changeByMobileDPI(20)
    },
    flexContainer:{
        flex:1,
        marginTop:metrics.changeByMobileDPI(5)
    },
    button: {
        borderRadius: metrics.changeByMobileDPI(11),
        height:metrics.changeByMobileDPI(34),
        width:metrics.changeByMobileDPI(93.75),
        overflow: 'hidden',
        alignSelf:'center'
      },
      externalStyle:{
        justifyContent:'center',
        alignItems:'center',
        flex:1
      },
      subscriptionFontStyle:{
        fontSize:font.size.font14,
        fontFamily:font.type.quicksandRegular,
        color:colors.black,
      },
      serviceFontStyle:{
        fontSize:font.size.font12,
        fontFamily:font.type.quicksandMedium,
        color:colors.graySolid,
      },
      flexRowContainer:{
        flexDirection:'row',
        alignItems:'center'
      },
      marginLeftContainer:{
        marginLeft:metrics.changeByMobileDPI(10)
      },
      svgContainer:{
        alignItems:'center'
      }
})
